package Viewer;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Ashan Lakshitha
 */
public class Advance_Search extends javax.swing.JDialog {

    /**
     * Creates new form Advance_Search
     */
    public Advance_Search(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lbl3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(14, 1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("-- Product Reports --");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl1.setText("Product Search");
        lbl1.setOpaque(true);
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl1MouseEntered(evt);
            }
        });
        jPanel1.add(lbl1);

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl2.setText("Available Stock Search");
        lbl2.setOpaque(true);
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl2MouseEntered(evt);
            }
        });
        jPanel1.add(lbl2);

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl3.setOpaque(true);
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl3MouseExited(evt);
            }
        });
        jPanel1.add(lbl3);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("-- Sales Reports --");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);

        lbl4.setBackground(new java.awt.Color(255, 255, 255));
        lbl4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl4.setText("Invoice Search");
        lbl4.setOpaque(true);
        lbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl4MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl4MouseClicked(evt);
            }
        });
        jPanel1.add(lbl4);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("-- Buying Reports --");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);

        lbl9.setBackground(new java.awt.Color(255, 255, 255));
        lbl9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl9.setText("Stock  Search ( GRN )");
        lbl9.setOpaque(true);
        lbl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl9MouseExited(evt);
            }
        });
        jPanel1.add(lbl9);

        jPanel2.setLayout(new java.awt.CardLayout());

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(668, 462));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(668, 462));
        jDesktopPane1.setLayout(new java.awt.CardLayout());
        jPanel2.add(jDesktopPane1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int selectedi;
    
    private void lbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseEntered
        if(selectedi == 1){
        
        }else{
            scrollenter(lbl1);
        }
    }//GEN-LAST:event_lbl1MouseEntered

    private void lbl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseExited
        if(selectedi == 1){
        
        }else{
            scrollexit(lbl1);
        }
    }//GEN-LAST:event_lbl1MouseExited

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        jDesktopPane1.removeAll();
        search_product sc = new search_product();
        jDesktopPane1.add(sc).setVisible(true);
        sc.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        selectedi = 1;
        setselectedlabel(lbl1);
    }//GEN-LAST:event_lbl1MouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        jDesktopPane1.removeAll();
        search_stock sc = new search_stock();
        jDesktopPane1.add(sc).setVisible(true);
        sc.setSize(jDesktopPane1.getWidth() , jDesktopPane1.getHeight());
        selectedi = 2;
        setselectedlabel(lbl2);
    }//GEN-LAST:event_lbl2MouseClicked

    private void lbl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseExited
        if(selectedi == 2){
        
        }else{
            scrollexit(lbl2);
        }
    }//GEN-LAST:event_lbl2MouseExited

    private void lbl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseEntered
        if(selectedi == 2){
        
        }else{
            scrollenter(lbl2);
        }
    }//GEN-LAST:event_lbl2MouseEntered

    private void lbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseClicked
        jDesktopPane1.removeAll();
        search_invoice sc = new search_invoice();
        jDesktopPane1.add(sc).setVisible(true);
        sc.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        selectedi = 4;
        setselectedlabel(lbl4);
    }//GEN-LAST:event_lbl4MouseClicked

    private void lbl4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseExited
        if(selectedi == 4){
        
        }else{
            scrollexit(lbl4);
        }
    }//GEN-LAST:event_lbl4MouseExited

    private void lbl4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseEntered
        if(selectedi == 4){
        
        }else{
            scrollenter(lbl4);
        }
    }//GEN-LAST:event_lbl4MouseEntered

    private void lbl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseExited
        if(selectedi == 3){

        }else{
            scrollexit(lbl3);
        }
    }//GEN-LAST:event_lbl3MouseExited

    private void lbl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseEntered
        if(selectedi == 3){

        }else{
            scrollenter(lbl3);
        }
    }//GEN-LAST:event_lbl3MouseEntered

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        jDesktopPane1.removeAll();
        search_warranty_date sc = new search_warranty_date();
        jDesktopPane1.add(sc).setVisible(true);
        sc.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        selectedi = 3;
        setselectedlabel(lbl3);
    }//GEN-LAST:event_lbl3MouseClicked

    private void lbl9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl9MouseEntered

    private void lbl9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl9MouseExited

    private void lbl9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl9MouseClicked
        jDesktopPane1.removeAll();
        search_stockgrn sc = new search_stockgrn();
        jDesktopPane1.add(sc).setVisible(true);
        sc.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        selectedi = 9;
        setselectedlabel(lbl9);
    }//GEN-LAST:event_lbl9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Advance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Advance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Advance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Advance_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Advance_Search dialog = new Advance_Search(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl9;
    // End of variables declaration//GEN-END:variables

    private void sethome() {
    /*
        jDesktopPane1.removeAll();
        homeadvancepanel sc = new homeadvancepanel();
        jDesktopPane1.add(sc).setVisible(true);
        sc.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
    */
    }
    
    private void setselectedlabel(JLabel jl){
        
        lbl1.setBackground(Color.white);
        lbl1.setForeground(Color.black);
        
        lbl2.setBackground(Color.white);
        lbl2.setForeground(Color.black);
        
        lbl3.setBackground(Color.white);
        lbl3.setForeground(Color.black);
        
        lbl4.setBackground(Color.white);
        lbl4.setForeground(Color.black);
        
        lbl9.setBackground(Color.white);
        lbl9.setForeground(Color.black);
        
        jl.setBackground(Color.black);
        jl.setForeground(Color.white);
    }
    
    private void scrollenter(JLabel jl){
        jl.setBackground(Color.DARK_GRAY);
        jl.setForeground(Color.white);
    }
    
    private void scrollexit(JLabel jl){
        jl.setBackground(Color.white);
        jl.setForeground(Color.black);
    
    }
    
}
