/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Viewer;

import Model.DB;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author Ashan Lakshitha
 */
public class DamageReturn extends javax.swing.JDialog {

    /**
     * Creates new form InvoiceReturn
     */
    DB d = new DB();
    DefaultTableModel dtm;
    DefaultTableModel dtm1;
    String user = "admin";
    
    DefaultListModel jlm1 ;
    private int Xmouse;
    private int Ymouse;
    
    public DamageReturn(java.awt.Frame parent, boolean modal ,String u) {
        super(parent, modal);
        initComponents();
        user = u;
        jlm1 = new DefaultListModel();
        dtm = (DefaultTableModel) invtable.getModel();
        setFrontText();
        numberlist1.setVisible(false);
        numberlist2.setVisible(false);
        
    }
    
    private void setFrontText(){
        setPront(jTextField1 , "Qty");
    }
    
    private void setPront(JTextField a , String text) {
        PromptSupport.setPrompt(text, a);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        numberlist2 = new javax.swing.JScrollPane();
        numberlist1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        invtable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cpidtxt = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberlist1.setBackground(new java.awt.Color(0, 0, 0));
        numberlist1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        numberlist1.setForeground(new java.awt.Color(255, 255, 255));
        numberlist1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        numberlist1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberlist1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        numberlist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberlist1MouseClicked(evt);
            }
        });
        numberlist1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberlist1KeyReleased(evt);
            }
        });
        numberlist1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                numberlist1ValueChanged(evt);
            }
        });
        numberlist2.setViewportView(numberlist1);

        jPanel3.add(numberlist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 330, 160));

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        invtable.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        invtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Batch No#", "Price", "Av Qty", "Return_Qty", "Ex Date", "Supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invtable.setRowHeight(20);
        invtable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        invtable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                invtableFocusGained(evt);
            }
        });
        invtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invtableMouseClicked(evt);
            }
        });
        invtable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                invtablePropertyChange(evt);
            }
        });
        invtable.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                invtableVetoableChange(evt);
            }
        });
        jScrollPane2.setViewportView(invtable);
        if (invtable.getColumnModel().getColumnCount() > 0) {
            invtable.getColumnModel().getColumn(0).setPreferredWidth(35);
            invtable.getColumnModel().getColumn(1).setPreferredWidth(100);
            invtable.getColumnModel().getColumn(2).setPreferredWidth(25);
            invtable.getColumnModel().getColumn(3).setPreferredWidth(30);
            invtable.getColumnModel().getColumn(4).setPreferredWidth(25);
            invtable.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 660, 200));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Return List");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Add to");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/desktop-pc-computer-128.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, -1));

        jButton1.setText("Add to Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 110, 40));

        cpidtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpidtxtKeyReleased(evt);
            }
        });
        jPanel3.add(cpidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 200, 30));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 160, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int selected = 0;
    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseReleased

    private void invtableVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_invtableVetoableChange
        //
    }//GEN-LAST:event_invtableVetoableChange

    private void invtablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_invtablePropertyChange
        //
    }//GEN-LAST:event_invtablePropertyChange

    private void invtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invtableMouseClicked
        
    }//GEN-LAST:event_invtableMouseClicked

    private void invtableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_invtableFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_invtableFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        savereturn();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numberlist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberlist1MouseClicked
        String cnum = numberlist1.getSelectedValue().toString();
        String arr[] = cnum.split(" - ", 2);
        loadtable();
        numberlist1.setVisible(false);
        numberlist2.setVisible(false);
    }//GEN-LAST:event_numberlist1MouseClicked

    private void numberlist1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberlist1KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String cnum = numberlist1.getSelectedValue().toString();
            String arr[] = cnum.split(" - ", 2);
            cpidtxt.setText(arr[0]);
            loadtable();
            numberlist1.setVisible(false);
            numberlist2.setVisible(false);
        }
    }//GEN-LAST:event_numberlist1KeyReleased

    private void numberlist1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_numberlist1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_numberlist1ValueChanged

    private void cpidtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpidtxtKeyReleased
        if(cpidtxt.getText().isEmpty()){
            numberlist1.setVisible(false);
            numberlist2.setVisible(false);
            clear(2);
        }else {
            searchproduct();
        }
        
        if(numberlist1.isVisible()){
            if(evt.getKeyCode() == KeyEvent.VK_DOWN){
                
                if(numberlist1.getModel().getSize() == 0){
                
                }else{
                    numberlist1.requestFocus();
                    numberlist1.setSelectedIndex(0);
                }
            }
        }
    }//GEN-LAST:event_cpidtxtKeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        
        String key = String.valueOf(c);
        
        if  (!(Character.isDigit(c) || key.equals(".") )) {
            evt.consume();
//	    Toolkit.getDefaultToolkit().beep();
        } 
        
        if(jTextField1.getText().contains(".") && key.equals(".")){
            evt.consume();
//	    Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DamageReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DamageReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DamageReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DamageReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DamageReturn dialog = new DamageReturn(new javax.swing.JFrame(), true ,  "dinesh");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpidtxt;
    private javax.swing.JTable invtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList numberlist1;
    private javax.swing.JScrollPane numberlist2;
    // End of variables declaration//GEN-END:variables

    
    private void loadtable() {
        
        try {
            dtm.setRowCount(0);
            
            ResultSet rs = d.srh("SELECT * FROM stock inner join product on "
                    + "stock.product_id = product.id "
                    + "inner join supplier on stock.supplier_id = supplier.id "
                    + "where stock.product_id = '"+cpidtxt.getText()+"'  ");
            while (rs.next()) {                
                Vector v = new Vector();
                v.add(rs.getString("product_id"));
                v.add(rs.getString("product.name"));
                v.add(rs.getString("stock.id"));
                v.add(rs.getDouble("buyprice"));
                v.add(rs.getDouble("avqty"));
                v.add(rs.getDouble("rqty"));
                v.add(rs.getString("exdate"));
                v.add(rs.getString("supplier.name"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    
    }


    private void savereturn() {
        try {
            
            if(invtable.getSelectedRow() == -1){
                JOptionPane.showMessageDialog(this, "Please Select item first");
            }else if(jTextField1.getText() == ""){
                JOptionPane.showMessageDialog(this, "Please insert qty");
            }else{
                    
                    int selectedrow = invtable.getSelectedRow();
                    String stockid = invtable.getValueAt(selectedrow, 2).toString();
                    
                    int i = d.aud("update stock set active = 2 , rlist = '"+jTextField1.getText()+"' where id = '"+stockid+"' ");
                    
                    
                    if(i == 1 ){
                        JOptionPane.showMessageDialog(this, "Return Added Sucess");
                        jTextField1.setText("");
                    }else{
                        JOptionPane.showMessageDialog(this, "Something Went Wrong ...");
                    }
                    
                    loadtable();
                }      
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    private void clear(int i) {
        
    }

    
    /*
    private void returnPro() {
        int a = 0; 
        int b = 0;
        int c = 0;
        
        try {
                int maxid = d.nextnum("select max(rid) from invoice_return", "max(rid)");
                
                for (int i = 0; i < returntable.getRowCount(); i++) {
                    String invid = invsearchtxt.getText();
                    String saleid = returntable.getValueAt(i, 1).toString();
                    String proid = returntable.getValueAt(i, 2).toString();
                    String subtotal = returntable.getValueAt(i, 7).toString();
                    String price = returntable.getValueAt(i, 5).toString();
                    String rstockid = returntable.getValueAt(i, 4).toString();
                    String rqty =  returntable.getValueAt(i, 6).toString();
                    String cus =  returntable.getValueAt(i, 8).toString();
                    
                    b = d.aud("insert into invoice_return(  invoice_saleid, invoice_invoice_reg_id, invoice_stock_id, invoice_stock_product_id, qty, price, total ,rdate , rid , cus ) "
                            + "Values( '"+saleid+"' , '"+invid+"' , '"+rstockid+"' , '"+proid+"' , '"+rqty+"' , '"+price+"' , '"+subtotal+"' , NOW() , '"+maxid+"'  , '"+cus+"' )");
                    a = d.aud("update stock set avqty = avqty + '"+rqty+"' where id = '"+rstockid+"' ");
                    a = d.aud("update invoice set rqty = rqty + '"+rqty+"' where saleid = '"+saleid+"' ");
                    d.aud("update customer set balance = balance - '"+subtotal+"' where id = '"+cus+"' ");
                    
                    
                }
                
                if(a==1 | b==1){
                    JOptionPane.showMessageDialog(this, "Return Products Successfully. ");
                    //printReport(maxid);
                    clear(5);
                }else{
                    JOptionPane.showMessageDialog(this, "Return Failed ");
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    
    }

*/
    

    private void printReport(int returnid) {
        try {
            //1 compile jrxm file
        JasperReport jr = JasperCompileManager.compileReport(getClass().getResourceAsStream("/Reports/Return-reciept.jrxml"));
        //2insert paramters
        java.util.Map m = new java.util.HashMap();
        m.put("ID", returnid);
        //3 run engine
        JasperPrint jp = JasperFillManager.fillReport(jr, m, d.getConnection());
        //4 view result
        //JasperViewer.viewReport(jp, false);
        //JRViewer jv = new JRViewer(jp);
        JasperPrintManager.printReport(jp, true);
        //
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    private void searchproduct() {
    
        try {
                    numberlist1.setVisible(true);
                    numberlist2.setVisible(true);
                    jlm1.removeAllElements();
                    ResultSet rs = d.srh("select *  from product where id LIKE '%"+cpidtxt.getText()+"%' OR name LIKE '%"+cpidtxt.getText()+"%' ");
                    for (int j = 0; rs.next(); j++) {
                        jlm1.add(j, rs.getString("id") + " - " + rs.getString("name") );
                    }
                    numberlist1.setModel(jlm1);

                    if(numberlist1.getModel().getSize() == 0){
                        numberlist1.setVisible(false);
                        clear(2);
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
    
    }
    
}
