/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Viewer;

import Model.DB;
import Model.Display;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashan Lakshitha
 */



public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    String user = "admin";
    String usertype = "admin";
    DefaultTableModel dtm , dtm2 , dtm3;
    DB d = new DB();
    
    public MainFrame(String loginuser , String type) {
        setbackground();
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setTitle("POS ");
        user = loginuser;
        usertype = type;
        shopname();
        setuser();
        dtm = (DefaultTableModel) lowstocktable.getModel();
        dtm2 = (DefaultTableModel) lowstocktable1.getModel();
        loadlowstock();
        loadexp();
        
        /*
        Display display=new Display();
        display.StartDisplay();   //optimal choice is start when system start.
        display.PrintFirstLine(" * SUGANDIKA SUPER * ");
        display.PrintSecondLine("NEXT CUSTOMER PLEASE");
        */
        
    }
    
    
    public void setbackground(){
        // Set a background for JFrame
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        int rheight = (int) height ;
        int rwidth = (int) width ;
            
        BufferedImage img = null;
        Image dimg = null;
        try {
            //img = ImageIO.read(new File("C:\\Users\\Thisara Sampath\\Desktop\\background.jpg"));
            img = ImageIO.read(getClass().getResource("/Image/back.png"));
            dimg = img.getScaledInstance(rwidth , rheight ,Image.SCALE_SMOOTH);
        }catch (IOException e) {
            e.printStackTrace();
        }
        
        this.setContentPane(new JLabel(new ImageIcon(dimg)));
        
        // Set some layout, say FlowLayout
        this.setLayout(new FlowLayout());
    }
    
    private void setsizes() {
            this.setSize(setMainSize());
            this.setLocationRelativeTo(null);
    }
    
    public Dimension setMainSize(){
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            double width = screenSize.getWidth();
            double height = screenSize.getHeight();
            int rheight = (int) height ;
            int rwidth = (int) width ;
            return screenSize;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        notifypanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lowstocktable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lowstocktable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        usernametxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usertypetxt = new javax.swing.JLabel();
        usertxt = new javax.swing.JLabel();
        nametxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        invoicemenu = new javax.swing.JMenuItem();
        usermenuitem1 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        grnmenu = new javax.swing.JMenuItem();
        lowstockitem1 = new javax.swing.JMenuItem();
        lowstockitem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        lowstockitem = new javax.swing.JMenuItem();
        lowstockitem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        suppreturnitem1 = new javax.swing.JMenuItem();
        suppreturnitem = new javax.swing.JMenuItem();
        adminmenu = new javax.swing.JMenu();
        usermenuitem = new javax.swing.JMenuItem();
        stockchange = new javax.swing.JMenuItem();
        invoicedel = new javax.swing.JMenuItem();
        deletestock = new javax.swing.JMenuItem();
        reportmenu = new javax.swing.JMenu();
        expireitem = new javax.swing.JMenuItem();
        dailysales = new javax.swing.JMenuItem();
        profitreport = new javax.swing.JMenuItem();
        advancesrh = new javax.swing.JMenuItem();
        profitreport1 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        expmenu = new javax.swing.JMenuItem();
        settings = new javax.swing.JMenu();
        profitreport3 = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        notifypanel.setBackground(new java.awt.Color(0, 0, 0));
        notifypanel.setMaximumSize(new java.awt.Dimension(243, 196));
        notifypanel.setMinimumSize(new java.awt.Dimension(243, 196));
        notifypanel.setPreferredSize(new java.awt.Dimension(243, 196));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/warning-sm.png"))); // NOI18N
        jLabel5.setText("Notifications");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Low Stock");

        lowstocktable.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        lowstocktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lowstocktable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(lowstocktable);

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("View ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh-circle-blue-24.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("View ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        lowstocktable1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        lowstocktable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lowstocktable1.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(lowstocktable1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Expire Management");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh-circle-blue-24.png"))); // NOI18N
        jLabel12.setText("jLabel8");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout notifypanelLayout = new javax.swing.GroupLayout(notifypanel);
        notifypanel.setLayout(notifypanelLayout);
        notifypanelLayout.setHorizontalGroup(
            notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notifypanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(notifypanelLayout.createSequentialGroup()
                        .addGroup(notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(notifypanelLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notifypanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        notifypanelLayout.setVerticalGroup(
            notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(notifypanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(notifypanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(notifypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        userpanel.setBackground(new java.awt.Color(0, 0, 0));
        userpanel.setMaximumSize(new java.awt.Dimension(243, 116));
        userpanel.setMinimumSize(new java.awt.Dimension(243, 116));

        usernametxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(255, 255, 255));
        usernametxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernametxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/male3-32.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Logout");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        usertypetxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usertypetxt.setForeground(new java.awt.Color(255, 255, 255));
        usertypetxt.setText("User Type");

        usertxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        usertxt.setForeground(new java.awt.Color(255, 255, 255));
        usertxt.setText("System User");

        nametxt.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        nametxt.setForeground(new java.awt.Color(255, 255, 255));
        nametxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nametxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cart.png"))); // NOI18N
        nametxt.setText("Name");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("- Minimize");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Daily Report");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userpanelLayout = new javax.swing.GroupLayout(userpanel);
        userpanel.setLayout(userpanelLayout);
        userpanelLayout.setHorizontalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usertxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(userpanelLayout.createSequentialGroup()
                                .addComponent(usertypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 31, Short.MAX_VALUE))))
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nametxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpanelLayout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        userpanelLayout.setVerticalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nametxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(usertypetxt))
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Software By Softmint Software Solutions - www.softmnt.net - 0777261026");
        jLabel1.setOpaque(true);

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon.png"))); // NOI18N
        jMenu6.setText("SOFTMINT POS");
        jMenu6.setEnabled(false);
        jMenu6.setFocusable(false);
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("SALES ");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        invoicemenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        invoicemenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        invoicemenu.setText("Create Invoice");
        invoicemenu.setMargin(new java.awt.Insets(5, 5, 5, 5));
        invoicemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicemenuActionPerformed(evt);
            }
        });
        jMenu7.add(invoicemenu);

        usermenuitem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usermenuitem1.setText("Invoice Return");
        usermenuitem1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        usermenuitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermenuitem1ActionPerformed(evt);
            }
        });
        jMenu7.add(usermenuitem1);

        jMenuBar1.add(jMenu7);

        jMenu9.setText("PURCHASING");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(5, 5, 5, 5));

        grnmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        grnmenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        grnmenu.setText("Create Stock");
        grnmenu.setMargin(new java.awt.Insets(5, 5, 5, 5));
        grnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnmenuActionPerformed(evt);
            }
        });
        jMenu9.add(grnmenu);

        lowstockitem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lowstockitem1.setText("Supplier Credits");
        lowstockitem1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        lowstockitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowstockitem1ActionPerformed(evt);
            }
        });
        jMenu9.add(lowstockitem1);

        lowstockitem3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lowstockitem3.setText("Print Barcode");
        lowstockitem3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        lowstockitem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowstockitem3ActionPerformed(evt);
            }
        });
        jMenu9.add(lowstockitem3);
        jMenu9.add(jSeparator2);

        lowstockitem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lowstockitem.setText("Low Stocks");
        lowstockitem.setMargin(new java.awt.Insets(5, 5, 5, 5));
        lowstockitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowstockitemActionPerformed(evt);
            }
        });
        jMenu9.add(lowstockitem);

        lowstockitem2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lowstockitem2.setText("Reorder Report");
        lowstockitem2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        lowstockitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowstockitem2ActionPerformed(evt);
            }
        });
        jMenu9.add(lowstockitem2);
        jMenu9.add(jSeparator1);

        suppreturnitem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        suppreturnitem1.setText("Add to Return");
        suppreturnitem1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        suppreturnitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppreturnitem1ActionPerformed(evt);
            }
        });
        jMenu9.add(suppreturnitem1);

        suppreturnitem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        suppreturnitem.setText("Supplier Return");
        suppreturnitem.setMargin(new java.awt.Insets(5, 5, 5, 5));
        suppreturnitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppreturnitemActionPerformed(evt);
            }
        });
        jMenu9.add(suppreturnitem);

        jMenuBar1.add(jMenu9);

        adminmenu.setText("ADMIN");
        adminmenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminmenu.setMargin(new java.awt.Insets(5, 5, 5, 5));

        usermenuitem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usermenuitem.setText("User Management");
        usermenuitem.setMargin(new java.awt.Insets(5, 5, 5, 5));
        usermenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermenuitemActionPerformed(evt);
            }
        });
        adminmenu.add(usermenuitem);

        stockchange.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        stockchange.setText("Stock Change");
        stockchange.setMargin(new java.awt.Insets(5, 5, 5, 5));
        stockchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockchangeActionPerformed(evt);
            }
        });
        adminmenu.add(stockchange);

        invoicedel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        invoicedel.setText("Delete Bills");
        invoicedel.setMargin(new java.awt.Insets(5, 5, 5, 5));
        invoicedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicedelActionPerformed(evt);
            }
        });
        adminmenu.add(invoicedel);

        deletestock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        deletestock.setText("Delete Stock");
        deletestock.setMargin(new java.awt.Insets(5, 5, 5, 5));
        deletestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestockActionPerformed(evt);
            }
        });
        adminmenu.add(deletestock);

        jMenuBar1.add(adminmenu);

        reportmenu.setText("REPORT");
        reportmenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reportmenu.setMargin(new java.awt.Insets(5, 5, 5, 5));

        expireitem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        expireitem.setText("Expire Management");
        expireitem.setMargin(new java.awt.Insets(5, 5, 5, 5));
        expireitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expireitemActionPerformed(evt);
            }
        });
        reportmenu.add(expireitem);

        dailysales.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        dailysales.setText("Daily Sales Report");
        dailysales.setMargin(new java.awt.Insets(5, 5, 5, 5));
        dailysales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailysalesActionPerformed(evt);
            }
        });
        reportmenu.add(dailysales);

        profitreport.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        profitreport.setText("Profit Report");
        profitreport.setMargin(new java.awt.Insets(5, 5, 5, 5));
        profitreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitreportActionPerformed(evt);
            }
        });
        reportmenu.add(profitreport);

        advancesrh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        advancesrh.setText("Advance Search");
        advancesrh.setMargin(new java.awt.Insets(5, 5, 5, 5));
        advancesrh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancesrhActionPerformed(evt);
            }
        });
        reportmenu.add(advancesrh);

        profitreport1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        profitreport1.setText("Return Report");
        profitreport1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        profitreport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitreport1ActionPerformed(evt);
            }
        });
        reportmenu.add(profitreport1);

        jMenuBar1.add(reportmenu);

        jMenu10.setText("EXPENSES");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu10.setMargin(new java.awt.Insets(5, 5, 5, 5));

        expmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        expmenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        expmenu.setText("Create Expenses");
        expmenu.setMargin(new java.awt.Insets(5, 5, 5, 5));
        expmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expmenuActionPerformed(evt);
            }
        });
        jMenu10.add(expmenu);

        jMenuBar1.add(jMenu10);

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GearsTurning-32.png"))); // NOI18N
        settings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        settings.setMargin(new java.awt.Insets(5, 5, 5, 5));

        profitreport3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        profitreport3.setText("Backup Database");
        profitreport3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        profitreport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitreport3ActionPerformed(evt);
            }
        });
        settings.add(profitreport3);

        jMenuBar1.add(settings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notifypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {notifypanel, userpanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notifypanel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new lowstock(this, false).setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        loadlowstock();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void suppreturnitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppreturnitemActionPerformed
        new Supplier_Return(this, false , user).setVisible(true);
    }//GEN-LAST:event_suppreturnitemActionPerformed

    private void expireitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expireitemActionPerformed
        new ExpireManagemnt(this, false).setVisible(true);
    }//GEN-LAST:event_expireitemActionPerformed

    private void lowstockitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowstockitemActionPerformed
        new lowstock(this, false).setVisible(true);
    }//GEN-LAST:event_lowstockitemActionPerformed

    private void usermenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermenuitemActionPerformed
        new user_registeration(this, false).setVisible(true);
    }//GEN-LAST:event_usermenuitemActionPerformed

    private void grnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnmenuActionPerformed
        new grn(this, false , user ).setVisible(true);
    }//GEN-LAST:event_grnmenuActionPerformed

    private void invoicemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicemenuActionPerformed
        new invoice(this, false , user ).setVisible(true);
    }//GEN-LAST:event_invoicemenuActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new ExpireManagemnt(this, false).setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        loadexp();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void stockchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockchangeActionPerformed
        new updatestock(this, false).setVisible(true);
    }//GEN-LAST:event_stockchangeActionPerformed

    private void deletestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestockActionPerformed
        new deletestock(this, false).setVisible(true);
    }//GEN-LAST:event_deletestockActionPerformed

    private void lowstockitem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowstockitem1ActionPerformed
        new Debit(this, false , user).setVisible(true);
    }//GEN-LAST:event_lowstockitem1ActionPerformed

    private void profitreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitreportActionPerformed
        new Report_SalesProfit(this, false).setVisible(true);
    }//GEN-LAST:event_profitreportActionPerformed

    private void dailysalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailysalesActionPerformed
        new SaleReport(this, false).setVisible(true);
    }//GEN-LAST:event_dailysalesActionPerformed

    private void advancesrhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancesrhActionPerformed
        new Advance_Search(this, false).setVisible(true);
    }//GEN-LAST:event_advancesrhActionPerformed

    private void lowstockitem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowstockitem2ActionPerformed
        new reorder(this, false).setVisible(true);
    }//GEN-LAST:event_lowstockitem2ActionPerformed

    private void suppreturnitem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppreturnitem1ActionPerformed
        new DamageReturn(this, false , user).setVisible(true);
    }//GEN-LAST:event_suppreturnitem1ActionPerformed

    private void profitreport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitreport1ActionPerformed
        new SupplierReturnReport(this, false , user).setVisible(true);
    }//GEN-LAST:event_profitreport1ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed

    }//GEN-LAST:event_jMenu7ActionPerformed

    private void invoicedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicedelActionPerformed
        new deleteinvoice(this, false).setVisible(true);
    }//GEN-LAST:event_invoicedelActionPerformed

    private void profitreport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitreport3ActionPerformed
        new Exec_Upload(this, false).setVisible(true);
    }//GEN-LAST:event_profitreport3ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(1);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new SaleReport(this, false).setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void usermenuitem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermenuitem1ActionPerformed
        new InvoiceReturn(this, false , user).setVisible(true);
    }//GEN-LAST:event_usermenuitem1ActionPerformed

    private void expmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expmenuActionPerformed
        new Expenses(this, false , user).setVisible(true);
    }//GEN-LAST:event_expmenuActionPerformed

    private void lowstockitem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowstockitem3ActionPerformed
        new barcodeprint(this, false).setVisible(true);
    }//GEN-LAST:event_lowstockitem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame("admin" , "admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminmenu;
    private javax.swing.JMenuItem advancesrh;
    private javax.swing.JMenuItem dailysales;
    private javax.swing.JMenuItem deletestock;
    private javax.swing.JMenuItem expireitem;
    private javax.swing.JMenuItem expmenu;
    private javax.swing.JMenuItem grnmenu;
    private javax.swing.JMenuItem invoicedel;
    private javax.swing.JMenuItem invoicemenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem lowstockitem;
    private javax.swing.JMenuItem lowstockitem1;
    private javax.swing.JMenuItem lowstockitem2;
    private javax.swing.JMenuItem lowstockitem3;
    private javax.swing.JTable lowstocktable;
    private javax.swing.JTable lowstocktable1;
    private javax.swing.JLabel nametxt;
    private javax.swing.JPanel notifypanel;
    private javax.swing.JMenuItem profitreport;
    private javax.swing.JMenuItem profitreport1;
    private javax.swing.JMenuItem profitreport3;
    private javax.swing.JMenu reportmenu;
    private javax.swing.JMenu settings;
    private javax.swing.JMenuItem stockchange;
    private javax.swing.JMenuItem suppreturnitem;
    private javax.swing.JMenuItem suppreturnitem1;
    private javax.swing.JMenuItem usermenuitem;
    private javax.swing.JMenuItem usermenuitem1;
    private javax.swing.JLabel usernametxt;
    private javax.swing.JPanel userpanel;
    private javax.swing.JLabel usertxt;
    private javax.swing.JLabel usertypetxt;
    // End of variables declaration//GEN-END:variables

    private void loadlowstock() {
    
        dtm.setRowCount(0);
        try {
            ResultSet rs = d.srh("select product.id , product.name , supplier.name , avg(lowstock) as ls , sum(avqty) as aq from stock\n" +
"inner join product on product.id = stock.product_id\n" +
"inner join supplier on stock.supplier_id = supplier.id\n" +
"group by stock.product_id\n" +
"Having avg(lowstock) >= sum(avqty)");
            while (rs.next()) { 
               java.util.Vector v = new java.util.Vector();
               v.add(rs.getString("product.name"));
               v.add(rs.getString("aq"));
               dtm.addRow(v);
               
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    

    private void loadexp() {

        try
    {
      this.dtm2.setRowCount(0);
      
      String a = "date(now())";
      ResultSet rs = this.d.srh("select * from stock inner join product on stock.product_id = product.id where exdate <= " + a + " and avqty > 0 order by exdate");
      while (rs.next())
      {
        Vector v = new Vector();
        v.add(rs.getString("name"));
        v.add(rs.getString("exdate"));
        this.dtm2.addRow(v);
      }
    }
    catch (Exception e)
    {
      e.printStackTrace();
    }
    
    }
    
    private void shopname() {

    try{
      
      ResultSet rs = this.d.srh("select name from name");
      while (rs.next()){
        nametxt.setText(rs.getString("name"));
      }
      
    }catch (Exception e){
      e.printStackTrace();
    }
    
    }

    private void setuser() {
        usertxt.setText(user);
        usertypetxt.setText(usertype);
        setuseroptions();
    }
    
    private void setuseroptions(){
        
        jMenuBar1.remove(jMenu10);
    
        if(usertype.equals("cashier")){
            adminmenu.setVisible(false);
            reportmenu.setVisible(false);
            settings.setVisible(false);
            jLabel4.setVisible(false);
            invoicedel.setVisible(false);
        }else{
            System.out.println("admin");
        }
    
    }


}
